TierService:
  Db:
    LogsConnString:
      settings-key: TierService-LogsConnString
      types: [AzureTableStorage]
    DataConnString:
      settings-key: TierService-DataConnString
      types: [AzureTableStorage]
    ClientPersonalInfoConnString:
      settings-key: TierService-ClientPersonalInfoConnString
      types: [AzureTableStorage]
  Countries:
    LowRisk:
      settings-key: TierService-Countries-LowRisk
      types: [JsonArray]
    MidRisk:
      settings-key: TierService-Countries-MidRisk
      types: [JsonArray]
    HighRisk:
      settings-key: TierService-Countries-HighRisk
      types: [JsonArray]
  Cqrs:
    RabbitConnectionString:
      settings-key: TierService-Cqrs-RabbitConnectionString
      types: [RabbitMq]
  Redis:
    Configuration:
      settings-key: TierService-Redis-Configuration
      types: [Redis]
    InstanceName:
      settings-key: TierService-Redis-InstanceName
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [AzureTableStorage]
    QueueName:
      settings-key: SlackQueueName
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
ClientAccountServiceClient:
  ServiceUrl:
    settings-key: ClientAccountServiceUrl
PersonalDataServiceClient:
  ApiKey:
    settings-key: PersonalDataApiKey
  ServiceUri:
    settings-key: PersonalDataServiceUrl
TemplateFormatterServiceClient:
  ServiceUrl:
    settings-key: TemplateFormatterServiceUrl
KycServiceClient:
  ApiKey:
    settings-key: KycService-ApiKey
  ServiceUri:
    settings-key: KycServiceUrl

